### ISSUE TITLE
POKEAPI_URL is overwritten for later tests

### ISSUE THREAD

**Issue by nimonian** [corndeladmin/swe-js-supportbank#10]
https://github.com/corndeladmin/swe-js-supportbank/blob/60f78f3a54f97299e6dee51d097b670b3249a156/tests/exercises/day-3-exercise-2.test.js#L11

This seems to overwrite the value of `process.env.POKEAPI_URL` permanently, so that subsequent tests fail. I think we will need to think of another way of testing the use of the env var.

**Comment by AndrewYHuang** [comment]
oh, derp, we can probably use BeforeEach (though that feels a bit inelegant for some reason)

**Comment by nimonian** [comment]
yeah it undoes the need for the learner to set the environment variable correctly

**Comment by nimonian** [comment]
I also noticed that here

```js
  before(() => {
    process.env.POKEAPI_URL = 'https://pokeapi.co/api/v2'
  })
  ```
  
  the url is missing the trailing slash which means `URL` drops the `v2`

**Comment by nimonian** [comment]
Maybe something like this:

```js
import { strict as assert } from 'assert'
import { PokeAPI } from '../../exercises/pokeAPI.js'

describe('PokeAPI', () => {

    const memo = process.env.POKEAPI_URL

    beforeEach(() => {
        process.env.POKEAPI_URL = memo
    })

    it('should use the POKEAPI_URL environment variable', () => {
        const testUrl = 'TEST_URL'
        process.env.POKEAPI_URL = testUrl
        const api = new PokeAPI()
        assert.equal(api.url, testUrl)
    })

    it('should get a list of pokemon', async () => {
        const api = new PokeAPI()
        const pokemon = await api.getPokemonList()
        assert.ok(pokemon.length > 0)
        assert.ok(pokemon.includes('bulbasaur'))
    })

    it('should get details for a pokemon', async () => {
        const api = new PokeAPI()
        const details = await api.getPokemonDetails('bulbasaur')
        assert.equal(details.id, 1)
        assert.equal(details.name, 'bulbasaur')
        assert.ok(details.types.includes('grass'))
        assert.ok(details.types.includes('poison'))
    })
})
```

**Comment by AndrewYHuang** [comment]
Ahh, smart! I like that :)

**Comment by AndrewYHuang** [comment]
Oh, one quick thought - we might need to have `import 'dotenv/config'` at the start of the file, or `require: 'dotenv/config'` in the mocharc (if we haven't done so already)

**Comment by AndrewYHuang** [comment]
(Unless importing PokeAPI would properly use its `import 'dotenv/config'`)

**Comment by nimonian** [comment]
I tried it out

With all code for tests 1 and 2 correct, but moving around the import, here are the results for which tests out of 1 and 2 pass:

| | Learner imports | Learner does not import |
|---|---|---|
| Test imports |1 and 2 | 1 and 2 |
| Test does not import | 1 and 2 | 1 |

I think the top-right quadrant is probably and argument against dong the import in the test file.

The bottom-right is also a bit of an aberration because test 1 should probably fail in this case, but I don't see a way around that.

**Comment by AndrewYHuang** [comment]
Ahh nice! Yeah, the top-right is definitely not what we want! Bottom-left is _acceptable_, at least it doesn't fully pass the exercise!
